# -*- coding: utf-8 -*-
"""introduccion a python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9UAuVczHaX1pmQZpIs18OxGODBf2O4W

Obtener la suma de dos numeros
"""

num1=3
print(num1)
num2=5
print(num2)
suma=num1+num2
suma

"""Obtener el promedio de 3 numeros"""

print ("bienvenido")
num1=2
num3=8
num2=5
promedio=(num1+num2+num3)/3
promedio
print("el promedio es "+ str (promedio))

"""Utilizar la sentencia IF para indicar si un valor es mayor que 50


"""

num1=70
if num1>50:
  print("la variable num1 es mayor que 50")
else:
    print ("la variable num1 es menor de 50")

"""Utilizar la sentencia IF-ELSE para indicar si una persona puede votar o no"""

edad=20
if edad >18:
  print ("Puede votar ")
  print ("ya que su edad es", edad)
else:
  print ("no puede votar")
  print ("ya que su edas es:", edad)

"""Leer informacion desde teclado, las lineas que tienen simbolo # han quedado como letreras ya que son otra forma de capturar informacion"""

#input("teclea tu numbre ")
nombre=input(" teclea tu numbre ")
print(nombre)
#print (input("teclea tu nombre "))
edad=input ("teclea tu edad ")
print (edad)

"""Elaborar un programa en Python que obtenga el área de un cuadrado, es necesario leer la base y
la altura.
"""

base = float(input(" Ingrese la longitud de la base: "))
altura = float (input(" Ingrese la altura: "))
area=base * altura
print(f"El area del cuadrado es: {area}")