# -*- coding: utf-8 -*-
"""Practicas ciclo FOR y WHILE ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCe-WeoXzWOdlcT6yKFmrx6wzEXZzIUT

**Leer números enteros en consola hasta que alguno sea mayor a 100**
"""

numero = int(input("Ingrese un numero entero: "))
while numero <= 100:
  print(f"El numero {numero} no es mayor a 100")
  numero = int(input("Ingrese otro numero: "))

  print(f"El numero {numero} si es mayor a 100")

"""**Escribir un programa que lea tantos números como quiere hasta que el número ingresado sea 0, como salida, que imprima la suma de todos los números ingresados.**"""

suma = 0
numero = float (input ("Ingrese un numero: "))

while numero != 0:
  suma += numero
  numero = float (input ("Ingrese otro numero. (0=Salir) "))

print(f"La suma de los numeros ingresados es: {suma}")

"""**Desarrollar un programa que permita la carga de 10 valores por teclado y nos muestre
posteriormente la suma de los valores ingresados y su promedio**
"""

suma = 0
contador = 0

print ("Ingrese 10 valores numericos: ")
while contador < 10:
  valor = float (input(f"Ingrese el valor #{contador + 1}: "))
  suma += valor
  contador += 1
promedio = suma/10
print (f"Total: {suma}")
print (f"Promedio: {promedio}")

"""**Escribir un programa que solicite por teclado 10 notas de alumnos y nos informe cuántos tienen
notas mayores o iguales a 7 y cuántos menores.**
"""

contador = 0
aprovados = 0
reprobados = 0

print("Ingrese 10 notas de alumnos: " )

while contador < 10:
  nota = float (input(f"Ingrese  la nota #{contador + 1} 5: "))
  if nota >= 7:
      aprovados += 1
  else :
    reprobados += 1

  contador += 1

print(f"Alumnos con notas mayores o iguales a 70: {aprovados}")
print(f"Alumnos con notas menores a 70: {reprobados}")

"""FOR

Leer números enteros en consola hasta que alguno sea mayor a 100
"""

for _ in iter (int, 1):
  numero = int (input("Ingrese un numero: "))
  if numero > 100:
                print (f"Numero mayor a 100: {numero} ")
                break

"""Escribir un programa que lea tantos números como quiere hasta que el número ingresado sea 0,
como salida, que imprima la suma de todos los números ingresados.


"""

suma = 0
for _ in iter(int, 1 ):
  numero = float (input("Ingrese un numero. 0 = Salir "))
  if numero == 0:
    break
  suma +=numero
print(f"La suma de los numeros ingresados es: {suma}")

"""Desarrollar un programa que permita la carga de 10 valores por teclado y nos muestre
posteriormente la suma de los valores ingresados y su promedio.


"""

suma = 0
for i in range (10):
  valor = float (input(f"Ingrese valor # {i+1}: "))
  suma += valor

promedio = suma / 10
print(f"Suma de los valores: {suma} ")
print(f"Promedio: {promedio} ")

"""Escribir un programa que solicite por teclado 10 notas de alumnos y nos informe cuántos tienen
notas mayores o iguales a 7 y cuántos menores.



"""

aprobados = 0
reprobados = 0
for i in range (10):
  nota = float(input(f"Ingrese nota del alumno {i+1}: "))
  if nota >= 7:
    aprobados += 1
  else:
    reprobados += 1

print (f"Alumnons aprovados: {aprobados}")
print (f"Alumnons aprovados: {reprobados}")

"""Definir la función suma, resta, multiplicación y División, posteriormente leer dos números,
mostrar un menú donde se seleccione una operación y mostrar el resultado.
"""

def suma (a,b):
  return a+b

def resta (a,b):
  return a-b

def multipli (a,b):
  return a*b

def division (a,b):
  return a/b if b!=0 else "division por cero!"

num1= float (input("Ingrese el primer numero : "))
num2= float (input("Ingrese el segundo numero : "))

print ("1 = Suma")
print ("2 = Restar")
print ("3 = Multiplicar")
print ("4 = Dividir ")

opcion = input("ingrese operacion ")

if opcion == '1' :
  print(f"Resultado: {suma(num1,num2)}")
elif opcion== '2':
  print (f"Resultado {resta(num1,num2)}")
elif opcion == '3':
  print (f"Resultado {multipli(num1,num2)}")
elif opcion == '4':
  print (f"Resultado {division(num1,num2)}")
else:
  print("entrada no valida")

""